export type BibleBook = {
  id: number;
  code: string;
  testament: "OT" | "NT";
  chapters: number;
  name: { en: string; fr: string; pt: string };
  abbr: { en: string; fr: string; pt: string };
};

export const BIBLE_BOOKS: BibleBook[] = [
  { id: 1,  code: "gen", testament: "OT", chapters: 50,  name: { en: "Genesis",         fr: "Genèse",                  pt: "Gênesis"           }, abbr: { en: "Gen", fr: "Gn",   pt: "Gn"  } },
  { id: 2,  code: "exo", testament: "OT", chapters: 40,  name: { en: "Exodus",           fr: "Exode",                   pt: "Êxodo"             }, abbr: { en: "Exo", fr: "Ex",   pt: "Êx"  } },
  { id: 3,  code: "lev", testament: "OT", chapters: 27,  name: { en: "Leviticus",        fr: "Lévitique",               pt: "Levítico"          }, abbr: { en: "Lev", fr: "Lv",   pt: "Lv"  } },
  { id: 4,  code: "num", testament: "OT", chapters: 36,  name: { en: "Numbers",          fr: "Nombres",                 pt: "Números"           }, abbr: { en: "Num", fr: "Nb",   pt: "Nm"  } },
  { id: 5,  code: "deu", testament: "OT", chapters: 34,  name: { en: "Deuteronomy",      fr: "Deutéronome",             pt: "Deuteronômio"      }, abbr: { en: "Deu", fr: "Dt",   pt: "Dt"  } },
  { id: 6,  code: "jos", testament: "OT", chapters: 24,  name: { en: "Joshua",           fr: "Josué",                   pt: "Josué"             }, abbr: { en: "Jos", fr: "Jos",  pt: "Js"  } },
  { id: 7,  code: "jdg", testament: "OT", chapters: 21,  name: { en: "Judges",           fr: "Juges",                   pt: "Juízes"            }, abbr: { en: "Jdg", fr: "Jg",   pt: "Jz"  } },
  { id: 8,  code: "rut", testament: "OT", chapters: 4,   name: { en: "Ruth",             fr: "Ruth",                    pt: "Rute"              }, abbr: { en: "Rut", fr: "Rt",   pt: "Rt"  } },
  { id: 9,  code: "1sa", testament: "OT", chapters: 31,  name: { en: "1 Samuel",         fr: "1 Samuel",                pt: "1 Samuel"          }, abbr: { en: "1Sa", fr: "1S",   pt: "1Sm" } },
  { id: 10, code: "2sa", testament: "OT", chapters: 24,  name: { en: "2 Samuel",         fr: "2 Samuel",                pt: "2 Samuel"          }, abbr: { en: "2Sa", fr: "2S",   pt: "2Sm" } },
  { id: 11, code: "1ki", testament: "OT", chapters: 22,  name: { en: "1 Kings",          fr: "1 Rois",                  pt: "1 Reis"            }, abbr: { en: "1Ki", fr: "1R",   pt: "1Rs" } },
  { id: 12, code: "2ki", testament: "OT", chapters: 25,  name: { en: "2 Kings",          fr: "2 Rois",                  pt: "2 Reis"            }, abbr: { en: "2Ki", fr: "2R",   pt: "2Rs" } },
  { id: 13, code: "1ch", testament: "OT", chapters: 29,  name: { en: "1 Chronicles",     fr: "1 Chroniques",            pt: "1 Crônicas"        }, abbr: { en: "1Ch", fr: "1Ch",  pt: "1Cr" } },
  { id: 14, code: "2ch", testament: "OT", chapters: 36,  name: { en: "2 Chronicles",     fr: "2 Chroniques",            pt: "2 Crônicas"        }, abbr: { en: "2Ch", fr: "2Ch",  pt: "2Cr" } },
  { id: 15, code: "ezr", testament: "OT", chapters: 10,  name: { en: "Ezra",             fr: "Esdras",                  pt: "Esdras"            }, abbr: { en: "Ezr", fr: "Esd",  pt: "Ed"  } },
  { id: 16, code: "neh", testament: "OT", chapters: 13,  name: { en: "Nehemiah",         fr: "Néhémie",                 pt: "Neemias"           }, abbr: { en: "Neh", fr: "Né",   pt: "Ne"  } },
  { id: 17, code: "est", testament: "OT", chapters: 10,  name: { en: "Esther",           fr: "Esther",                  pt: "Ester"             }, abbr: { en: "Est", fr: "Est",  pt: "Et"  } },
  { id: 18, code: "job", testament: "OT", chapters: 42,  name: { en: "Job",              fr: "Job",                     pt: "Jó"                }, abbr: { en: "Job", fr: "Jb",   pt: "Jó"  } },
  { id: 19, code: "psa", testament: "OT", chapters: 150, name: { en: "Psalms",           fr: "Psaumes",                 pt: "Salmos"            }, abbr: { en: "Psa", fr: "Ps",   pt: "Sl"  } },
  { id: 20, code: "pro", testament: "OT", chapters: 31,  name: { en: "Proverbs",         fr: "Proverbes",               pt: "Provérbios"        }, abbr: { en: "Pro", fr: "Pr",   pt: "Pv"  } },
  { id: 21, code: "ecc", testament: "OT", chapters: 12,  name: { en: "Ecclesiastes",     fr: "Ecclésiaste",             pt: "Eclesiastes"       }, abbr: { en: "Ecc", fr: "Ec",   pt: "Ec"  } },
  { id: 22, code: "sng", testament: "OT", chapters: 8,   name: { en: "Song of Solomon",  fr: "Cantique des Cantiques",  pt: "Cântico dos Cânticos" }, abbr: { en: "Sng", fr: "Ct", pt: "Ct" } },
  { id: 23, code: "isa", testament: "OT", chapters: 66,  name: { en: "Isaiah",           fr: "Ésaïe",                   pt: "Isaías"            }, abbr: { en: "Isa", fr: "És",   pt: "Is"  } },
  { id: 24, code: "jer", testament: "OT", chapters: 52,  name: { en: "Jeremiah",         fr: "Jérémie",                 pt: "Jeremias"          }, abbr: { en: "Jer", fr: "Jr",   pt: "Jr"  } },
  { id: 25, code: "lam", testament: "OT", chapters: 5,   name: { en: "Lamentations",     fr: "Lamentations",            pt: "Lamentações"       }, abbr: { en: "Lam", fr: "Lm",   pt: "Lm"  } },
  { id: 26, code: "eze", testament: "OT", chapters: 48,  name: { en: "Ezekiel",          fr: "Ézéchiel",                pt: "Ezequiel"          }, abbr: { en: "Eze", fr: "Éz",   pt: "Ez"  } },
  { id: 27, code: "dan", testament: "OT", chapters: 12,  name: { en: "Daniel",           fr: "Daniel",                  pt: "Daniel"            }, abbr: { en: "Dan", fr: "Dn",   pt: "Dn"  } },
  { id: 28, code: "hos", testament: "OT", chapters: 14,  name: { en: "Hosea",            fr: "Osée",                    pt: "Oséias"            }, abbr: { en: "Hos", fr: "Os",   pt: "Os"  } },
  { id: 29, code: "joe", testament: "OT", chapters: 3,   name: { en: "Joel",             fr: "Joël",                    pt: "Joel"              }, abbr: { en: "Joe", fr: "Jl",   pt: "Jl"  } },
  { id: 30, code: "amo", testament: "OT", chapters: 9,   name: { en: "Amos",             fr: "Amos",                    pt: "Amós"              }, abbr: { en: "Amo", fr: "Am",   pt: "Am"  } },
  { id: 31, code: "oba", testament: "OT", chapters: 1,   name: { en: "Obadiah",          fr: "Abdias",                  pt: "Obadias"           }, abbr: { en: "Oba", fr: "Abd",  pt: "Ab"  } },
  { id: 32, code: "jon", testament: "OT", chapters: 4,   name: { en: "Jonah",            fr: "Jonas",                   pt: "Jonas"             }, abbr: { en: "Jon", fr: "Jon",  pt: "Jn"  } },
  { id: 33, code: "mic", testament: "OT", chapters: 7,   name: { en: "Micah",            fr: "Michée",                  pt: "Miquéias"          }, abbr: { en: "Mic", fr: "Mi",   pt: "Mq"  } },
  { id: 34, code: "nah", testament: "OT", chapters: 3,   name: { en: "Nahum",            fr: "Nahoum",                  pt: "Naum"              }, abbr: { en: "Nah", fr: "Na",   pt: "Na"  } },
  { id: 35, code: "hab", testament: "OT", chapters: 3,   name: { en: "Habakkuk",         fr: "Habacuc",                 pt: "Habacuque"         }, abbr: { en: "Hab", fr: "Ha",   pt: "Hc"  } },
  { id: 36, code: "zep", testament: "OT", chapters: 3,   name: { en: "Zephaniah",        fr: "Sophonie",                pt: "Sofonias"          }, abbr: { en: "Zep", fr: "So",   pt: "Sf"  } },
  { id: 37, code: "hag", testament: "OT", chapters: 2,   name: { en: "Haggai",           fr: "Aggée",                   pt: "Ageu"              }, abbr: { en: "Hag", fr: "Ag",   pt: "Ag"  } },
  { id: 38, code: "zec", testament: "OT", chapters: 14,  name: { en: "Zechariah",        fr: "Zacharie",                pt: "Zacarias"          }, abbr: { en: "Zec", fr: "Za",   pt: "Zc"  } },
  { id: 39, code: "mal", testament: "OT", chapters: 4,   name: { en: "Malachi",          fr: "Malachie",                pt: "Malaquias"         }, abbr: { en: "Mal", fr: "Ml",   pt: "Ml"  } },
  { id: 40, code: "mat", testament: "NT", chapters: 28,  name: { en: "Matthew",          fr: "Matthieu",                pt: "Mateus"            }, abbr: { en: "Mat", fr: "Mt",   pt: "Mt"  } },
  { id: 41, code: "mar", testament: "NT", chapters: 16,  name: { en: "Mark",             fr: "Marc",                    pt: "Marcos"            }, abbr: { en: "Mar", fr: "Mc",   pt: "Mc"  } },
  { id: 42, code: "luk", testament: "NT", chapters: 24,  name: { en: "Luke",             fr: "Luc",                     pt: "Lucas"             }, abbr: { en: "Luk", fr: "Lc",   pt: "Lc"  } },
  { id: 43, code: "joh", testament: "NT", chapters: 21,  name: { en: "John",             fr: "Jean",                    pt: "João"              }, abbr: { en: "Joh", fr: "Jn",   pt: "Jo"  } },
  { id: 44, code: "act", testament: "NT", chapters: 28,  name: { en: "Acts",             fr: "Actes",                   pt: "Atos"              }, abbr: { en: "Act", fr: "Ac",   pt: "At"  } },
  { id: 45, code: "rom", testament: "NT", chapters: 16,  name: { en: "Romans",           fr: "Romains",                 pt: "Romanos"           }, abbr: { en: "Rom", fr: "Rm",   pt: "Rm"  } },
  { id: 46, code: "1co", testament: "NT", chapters: 16,  name: { en: "1 Corinthians",    fr: "1 Corinthiens",           pt: "1 Coríntios"       }, abbr: { en: "1Co", fr: "1Co",  pt: "1Co" } },
  { id: 47, code: "2co", testament: "NT", chapters: 13,  name: { en: "2 Corinthians",    fr: "2 Corinthiens",           pt: "2 Coríntios"       }, abbr: { en: "2Co", fr: "2Co",  pt: "2Co" } },
  { id: 48, code: "gal", testament: "NT", chapters: 6,   name: { en: "Galatians",        fr: "Galates",                 pt: "Gálatas"           }, abbr: { en: "Gal", fr: "Ga",   pt: "Gl"  } },
  { id: 49, code: "eph", testament: "NT", chapters: 6,   name: { en: "Ephesians",        fr: "Éphésiens",               pt: "Efésios"           }, abbr: { en: "Eph", fr: "Éph",  pt: "Ef"  } },
  { id: 50, code: "phi", testament: "NT", chapters: 4,   name: { en: "Philippians",      fr: "Philippiens",             pt: "Filipenses"        }, abbr: { en: "Phi", fr: "Ph",   pt: "Fp"  } },
  { id: 51, code: "col", testament: "NT", chapters: 4,   name: { en: "Colossians",       fr: "Colossiens",              pt: "Colossenses"       }, abbr: { en: "Col", fr: "Col",  pt: "Cl"  } },
  { id: 52, code: "1th", testament: "NT", chapters: 5,   name: { en: "1 Thessalonians",  fr: "1 Thessaloniciens",       pt: "1 Tessalonicenses" }, abbr: { en: "1Th", fr: "1Th",  pt: "1Ts" } },
  { id: 53, code: "2th", testament: "NT", chapters: 3,   name: { en: "2 Thessalonians",  fr: "2 Thessaloniciens",       pt: "2 Tessalonicenses" }, abbr: { en: "2Th", fr: "2Th",  pt: "2Ts" } },
  { id: 54, code: "1ti", testament: "NT", chapters: 6,   name: { en: "1 Timothy",        fr: "1 Timothée",              pt: "1 Timóteo"         }, abbr: { en: "1Ti", fr: "1Tm",  pt: "1Tm" } },
  { id: 55, code: "2ti", testament: "NT", chapters: 4,   name: { en: "2 Timothy",        fr: "2 Timothée",              pt: "2 Timóteo"         }, abbr: { en: "2Ti", fr: "2Tm",  pt: "2Tm" } },
  { id: 56, code: "tit", testament: "NT", chapters: 3,   name: { en: "Titus",            fr: "Tite",                    pt: "Tito"              }, abbr: { en: "Tit", fr: "Tt",   pt: "Tt"  } },
  { id: 57, code: "phm", testament: "NT", chapters: 1,   name: { en: "Philemon",         fr: "Philémon",                pt: "Filemon"           }, abbr: { en: "Phm", fr: "Phm",  pt: "Fm"  } },
  { id: 58, code: "heb", testament: "NT", chapters: 13,  name: { en: "Hebrews",          fr: "Hébreux",                 pt: "Hebreus"           }, abbr: { en: "Heb", fr: "Hé",   pt: "Hb"  } },
  { id: 59, code: "jam", testament: "NT", chapters: 5,   name: { en: "James",            fr: "Jacques",                 pt: "Tiago"             }, abbr: { en: "Jam", fr: "Jc",   pt: "Tg"  } },
  { id: 60, code: "1pe", testament: "NT", chapters: 5,   name: { en: "1 Peter",          fr: "1 Pierre",                pt: "1 Pedro"           }, abbr: { en: "1Pe", fr: "1P",   pt: "1Pe" } },
  { id: 61, code: "2pe", testament: "NT", chapters: 3,   name: { en: "2 Peter",          fr: "2 Pierre",                pt: "2 Pedro"           }, abbr: { en: "2Pe", fr: "2P",   pt: "2Pe" } },
  { id: 62, code: "1jo", testament: "NT", chapters: 5,   name: { en: "1 John",           fr: "1 Jean",                  pt: "1 João"            }, abbr: { en: "1Jo", fr: "1Jn",  pt: "1Jo" } },
  { id: 63, code: "2jo", testament: "NT", chapters: 1,   name: { en: "2 John",           fr: "2 Jean",                  pt: "2 João"            }, abbr: { en: "2Jo", fr: "2Jn",  pt: "2Jo" } },
  { id: 64, code: "3jo", testament: "NT", chapters: 1,   name: { en: "3 John",           fr: "3 Jean",                  pt: "3 João"            }, abbr: { en: "3Jo", fr: "3Jn",  pt: "3Jo" } },
  { id: 65, code: "jud", testament: "NT", chapters: 1,   name: { en: "Jude",             fr: "Jude",                    pt: "Judas"             }, abbr: { en: "Jud", fr: "Jude", pt: "Jd"  } },
  { id: 66, code: "rev", testament: "NT", chapters: 22,  name: { en: "Revelation",       fr: "Apocalypse",              pt: "Apocalipse"        }, abbr: { en: "Rev", fr: "Ap",   pt: "Ap"  } },
];

export type VerseStore = Record<string, Record<number, Record<number, string>>>;